Repository B1lok/gym-web, pull requests merged in 2023-12, with the labels that each got.

#23 Added favicon and coaches page
  public/favicon.svg
  public/index.html
  src/pages/coaches/Coaches.jsx
  src/pages/coaches/components/CoachCard.jsx
Labels: enhancement

#25 Refactored pages
  src/pages/admin/staff/Staff.jsx
  src/pages/admin/staff/Staff.styles.js
  src/pages/admin/subscriptions/Subscriptions.jsx
  src/pages/admin/subscriptions/Subscriptions.styles.js
  src/pages/coaches/Coaches.jsx
  src/pages/coaches/components/CoachCard.jsx
  src/pages/coaches/constants/index.jsx
  src/pages/user/mySubscriptions/MySubscriptions.jsx
  src/pages/user/mySubscriptions/MySubscriptions.styles.js
  src/pages/user/mySubscriptions/components/UserSubscriptionCard.jsx
Labels: enhancement

#27 Refactoring
  src/components/common/layout/page-layout/PageLayout.jsx
  src/components/common/layout/page-layout/PageLayout.styles.js
  src/components/common/layout/sidebar/Sidebar.jsx
  src/components/common/layout/sidebar/Sidebar.styles.js
  src/pages/admin/dashboard/Dashboard.jsx
  src/pages/admin/subscriptions/Subscriptions.jsx
  src/pages/admin/subscriptions/Subscriptions.styles.js
  src/pages/sign-in/SignIn.jsx
  src/pages/sign-in/SignIn.styles.js
  src/pages/sign-up/SignUp.jsx
  src/pages/sign-up/SignUp.styles.js
  src/pages/user/my-subscriptions/MySubscriptions.jsx
  src/pages/user/my-subscriptions/MySubscriptions.styles.js
  src/pages/user/my-subscriptions/components/buy-subscription/BuySubscription.jsx
  src/pages/user/my-subscriptions/components/buy-subscription/BuySubscription.styles.js
  src/pages/user/my-subscriptions/components/buy-subscription/components/BuySubscriptionCard.jsx
  src/pages/user/my-subscriptions/components/buy-subscription/components/SubscriptionPurchaseDialog.jsx
  src/pages/user/my-subscriptions/components/user-subscription-card/UserSubscriptionCard.jsx
  src/pages/user/my-subscriptions/components/user-subscription-card/components/training-enroll-dialog/TrainingEnroll.jsx
  src/pages/user/my-subscriptions/components/user-subscription-card/components/training-enroll-dialog/TrainingEnroll.styles.js
  src/pages/user/my-subscriptions/components/user-subscription-card/components/user-trainings-table/UserTrainingsTable.jsx
  src/pages/user/my-subscriptions/components/user-subscription-card/components/user-trainings-table/UserTrainingsTable.styles.js
  src/pages/user/my-subscriptions/components/user-subscription-card/components/user-trainings-table/constants/index.jsx
  src/pages/user/mySubscriptions/MySubscriptions.styles.js
  src/pages/user/mySubscriptions/components/UserTrainingsGrid.jsx
  src/router/routes.js
  src/utils/utils.js
Labels: enhancement

#28 Added appropriate questions to faq page
  src/pages/faq/constants/index.jsx
Labels: documentation

#29 Fixed subscription error
  src/pages/user/my-subscriptions/components/buy-subscription/BuySubscription.jsx
  src/pages/user/my-subscriptions/components/buy-subscription/components/SubscriptionPurchaseDialog.jsx
Labels: bugfix
