Repository B1lok/gym-web, pull requests merged in 2023-11, with the labels that each got.

#4 Implemented basic sign in and sign up functionality
  package-lock.json
  package.json
  src/API/AuthService.js
  src/App.js
  src/context/authContext.js
  src/pages/Login.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/router/routes.js
  src/utils/constants.js
Labels: enhancement

#5 Changed validation messages
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: enhancement

#6 Renamed API to api
  src/api/AuthService.js
Labels: invalid

#7 Fixed imports
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: enhancement

#9 Refactored routing
  src/components/AppRouter.jsx
  src/router/routes.js
Labels: enhancement

#10 Implemented admin pages
  package-lock.json
  package.json
  src/api/AdminService.js
  src/api/CoachService.js
  src/api/SubscriptionService.js
  src/components/SubscriptionCard.jsx
  src/hooks/useFetching.js
  src/pages/admin/customers/Customers.jsx
  src/pages/admin/customers/components/UserSubscriptionsGrid.jsx
  src/pages/admin/customers/components/UserTrainingsGrid.jsx
  src/pages/admin/staff/Staff.jsx
  src/pages/admin/staff/components/AdminsGrid.jsx
  src/pages/admin/staff/components/CoachRecordsGrid.jsx
  src/pages/admin/staff/components/CoachesGrid.jsx
  src/pages/coach/records/Records.jsx
  src/router/routes.js
  src/utils/constants.js
Labels: enhancement

#11 Implemented header, footer and added page layout logic
  src/api/UserService.js
  src/components/common/layout/footer/Footer.jsx
  src/components/common/layout/footer/Footer.styles.js
  src/components/common/layout/footer/constants/index.jsx
  src/components/common/layout/header/Header.jsx
  src/components/common/layout/header/components/auth-buttons/AuthButtons.jsx
  src/components/common/layout/header/components/auth-buttons/AuthButtons.styles.js
  src/components/common/layout/header/components/header-desktop/HeaderDesktop.jsx
  src/components/common/layout/header/components/header-desktop/HeaderDesktop.styles.js
  src/components/common/layout/header/components/header-logo/HeaderLogo.jsx
  src/components/common/layout/header/components/header-logo/HeaderLogo.styles.js
  src/components/common/layout/header/components/header-mobile/HeaderMobile.jsx
  src/components/common/layout/header/components/header-mobile/HeaderMobile.styles.js
  src/components/common/layout/header/components/header-mobile/components/DrawerMenu/DrawerMenu.jsx
  src/components/common/layout/header/components/header-mobile/components/DrawerMenu/DrawerMenu.styles.js
  src/components/common/layout/header/constants/index.jsx
  src/components/common/layout/page-layout/PageLayout.jsx
  src/components/common/layout/page-layout/PageLayout.styles.js
  src/pages/faq/Faq.jsx
  src/utils/constants.js
Labels: enhancement

#13 Renamed folder Main to main
  src/pages/main/Main.jsx
  src/router/routes.js
Labels: bugfix

#14 Added styles, refactored a bit
  src/pages/faq/Faq.jsx
  src/pages/faq/Faq.styles.js
Labels: enhancement

#15 Subscription page implementation
  src/api/SubscriptionService.js
  src/pages/Subscriptions.jsx
  src/pages/Subscriptions1.jsx
  src/pages/admin/subscriptions/Subscriptions.jsx
  src/pages/admin/subscriptions/components/SubscriptionCard.jsx
  src/pages/admin/subscriptions/components/Subscriptions.styles.js
  src/pages/coaches/Coaches.style.js
  src/router/routes.js
Labels: enhancement

#16 Fixed admin routing
  src/router/routes.js
  src/utils/constants.js
Labels: bugfix

#17 Implemented pages
  package-lock.json
  package.json
  src/api/AdminService.js
  src/api/UserService.js
  src/pages/Subscriptions.jsx
  src/pages/admin/dashboard/Dashboard.jsx
  src/pages/admin/dashboard/components/Chart.jsx
  src/pages/admin/dashboard/components/StatBox.jsx
  src/pages/admin/dashboard/components/Statistics.jsx
  src/pages/user/buySubscription/BuySubscription.jsx
  src/pages/user/buySubscription/components/BuySubscriptionCard.jsx
  src/pages/user/mySubscriptions/MySubscriptions.jsx
  src/pages/user/mySubscriptions/components/TrainingEnroll.jsx
  src/pages/user/mySubscriptions/components/UserSubscriptionCard.jsx
  src/pages/user/mySubscriptions/components/UserTrainingsGrid.jsx
Labels: enhancement

#18 Implemented all routes
  src/pages/user/mySubscriptions/MySubscriptions.jsx
  src/pages/user/profile/Profile.jsx
  src/router/routes.js
  src/utils/constants.js
Labels: enhancement

#19 Sidebar
  src/components/common/layout/page-layout/PageLayout.styles.js
  src/components/common/layout/sidebar/Sidebar.jsx
  src/components/common/layout/sidebar/Sidebar.styles.js
  src/components/common/layout/sidebar/constants/index.jsx
  src/router/routes.js
  src/utils/constants.js
Labels: enhancement

#20 Implemented subscription purchase functionality
  src/api/CoachService.js
  src/api/UserService.js
  src/pages/user/buySubscription/BuySubscription.jsx
  src/pages/user/buySubscription/components/BuySubscriptionCard.jsx
  src/pages/user/mySubscriptions/MySubscriptions.jsx
  src/pages/user/mySubscriptions/buySubscription/BuySubscription.jsx
  src/pages/user/mySubscriptions/buySubscription/components/BuySubscriptionCard.jsx
  src/pages/user/mySubscriptions/buySubscription/components/SubscriptionPurchaseDialog.jsx
  src/pages/user/mySubscriptions/components/TrainingEnroll.jsx
  src/router/routes.js
Labels: enhancement

#22 Main implememtation
  public/img/gym-entry.jpg
  src/components/common/layout/sidebar/constants/index.jsx
  src/pages/admin/dashboard/Dashboard.styles.js
  src/pages/admin/subscriptions/Subscriptions.styles.js
  src/pages/admin/subscriptions/components/SubscriptionCard.jsx
  src/pages/main/Main.jsx
  src/pages/main/Main.styles.js
  src/pages/profile/Profile.jsx
  src/pages/sign-in/SignIn.jsx
  src/pages/sign-up/SignUp.jsx
  src/pages/user/mySubscriptions/MySubscriptions.jsx
Labels: enhancement
